[package]
name = "learn_wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = { version = "1.24.0", features = ["derive"] }
pollster = { version =  "0.4.0", features = ["macro"] }
wgpu = "28.0.0"
